### ISSUE TITLE
No CI?

### ISSUE THREAD

**Issue by mtwilliams** [gjaldon/ecto_enum#5]
Setting up for Travis CI would only require you to add a `.travis.yml`:

``` yaml
language: elixir
elixir:
  - 1.2.3
otp_release:
  - 18.2
addons:
  postgresql: "9.4"
# Use the new containerized infrastructure to build suppa fast.
sudo: false
# Run our test-suite.
script:
  - mix test
# Report documentation coverage to InchCI.
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
```
